### ISSUE TITLE
Questions regarding creation of point clouds and 3D visualizations

### ISSUE THREAD

**Issue by sriagastya** [SibylGao/MSCVP-MVSNet#1]
Hello, I came across your repository on paperswithcode.com and was amazed by the 3D visualizations on the README page. I am a researcher currently working on the Multi-view stereo problem. Please let me know which tools you've used to create point clouds and 3D visualizations. I would be really happy if you are aware of a Python library for the same. Thank you for your time.

**Comment by SibylGao** [comment]
Hi asrimanth ! 

For point clouds generation, please follow the standard post-processing tools [fusibile](https://github.com/kysucix/fusibile) provided by Galliani et al. If you prefer python scripts, try [depthfusion.py](https://github.com/YoYo000/MVSNet/blob/3ae2cb2b72c6df58ebcb321d7d243d4efd01fbc5/mvsnet/depthfusion.py) provided by Yao et al.

For 3D visualizations, I use Meshlab to visualize point clouds files.

Hope it helps.
